name: CMake

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        include:
        - name: windows-debug
          os: windows-latest
          build_config: Debug
        - name: windows-release
          os: windows-latest
          build_config: Release
        - name: linux-debug
          os: ubuntu-latest
          build_config: Debug
        - name: linux-release
          os: ubuntu-latest
          build_config: Release
        - name: macos-debug
          os: macos-latest
          build_config: Debug
        - name: macos-release
          os: macos-latest
          build_config: Release

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_config }} -DCMAKE_INSTALL_PREFIX=install

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_config }} --target install

    - name: Archive
      uses: actions/upload-artifact@v3
      with:
          name: build-${{ matrix.name }}
          path: install/**/*

