name: CMake

on: workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        cmake_config: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.cmake_config }} -DCMAKE_INSTALL_PREFIX=install

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.cmake_config }} --target install

    - name: Archive
      uses: actions/upload-artifact@v3
      with:
          name: build-${{ matrix.os }}-${{ matrix.cmake_config }}
          path: install/bin/hello-world.exe

